export class PantryWriter {
    /**
     * @param {Object} memoryPantry Reference to the global long-term archive repository.
     */
    constructor(memoryPantry) {
        this.pantry = memoryPantry;
    }

    /**
     * Commit a structural entry directly to the system logs interface
     */
    write(title, body) {
        const entry = {
            title,
            body,
            timestamp: new Date().toISOString()
        };

        if (this.pantry && typeof this.pantry.addEntry === "function") {
            this.pantry.addEntry(entry);
        }

        // Notify the central bus that a historical memory has been safely crystallized
        if (window.CATHEDRAL_CORE_BUS) {
            window.CATHEDRAL_CORE_BUS.publish("pantry.entry.created", entry);
        }
    }

    /**
     * Distill localized semantic maps down into structured neighborhood journals
     */
    writeClusterSummary(clusters) {
        const body = clusters
            .map((c, i) => `Cluster ${i + 1}: Contains ${c.length} related active nodes.`)
            .join("\n");

        this.write("Semantic Cluster Summary", `[TRANSCRIPT]\n${body}`);
    }

    /**
     * Record regional weather field fluctuations across the spatial coordinate grid
     */
    writeDriftWeather(contours) {
        const body = contours
            .map(c => `Barometric Isobar Level ${c.level}: Tracking ${c.points.length} turbulence markers.`)
            .join("\n");

        this.write("Drift Weather Snapshot", `[METEOROLOGY]\n${body}`);
    }

    /**
     * Save deep timeline event summaries generated by the compression engine
     */
    writePrecogCompression(packet) {
        const body = `Summary: ${packet.summary}\nStructural Weight: ${packet.importance}\nAggregated Frame Count: ${packet.count}`;
        this.write("Precog Compression Packet", `[DEEP MEMORY]\n${body}`);
    }

    /**
     * Document manual human-system diagnostic interactions across node ancestral paths
     */
    writeHUDInspection(nodeId, ancestryChain) {
        const body = `Inspected Target ID: ${nodeId}\nLineage Path Traversed: ${ancestryChain.join(" ➜ ")}`;
        this.write("HUD Inspection Log", `[PROCEDURAL ARCHAEOLOGY]\n${body}`);
    }
}

